### ISSUE TITLE
Force mods to check?

### ISSUE THREAD

**Issue by djoveryde** [gamerforEA/EventHelper#1]
Hi, sorry to keep bothering you, would this plugin force mods to check the region before firing event? I have players using items/guns in ProjectE and other mods which are bypassing WG Protection.

**Comment by djoveryde** [comment]
So I've found this actually prevents most items from bypassing protected regions so BIG thankyou for that. There are a few items however that still bypass. Gem Armor has an AOE explosive. Thats from ProjectE if you wanted to look into adding that to protection. Also if some things are directed at a player within a region it bypasses as a projectile.

**Comment by gamerforEA** [comment]
This mod itself will not help you. To add all the required checks must be modified each mode separately.
