### ISSUE TITLE
Patched mod advise for an old 1.5.2 server (voltz)

### ISSUE THREAD

**Issue by djoveryde** [gamerforEA/EventHelper#2]
After some advise. If I get an error of "java.lang.NoSuchFieldError: ticks" and the area that gives that error is "        ForgeDirection direction;
        if (this.ticks % 20 == 0) {
          for (int i = 0; i < 6; i++)"    What do you think I could do to fix it? Is it possible its looking for an addon that gives that particular term.
The server doesn't seem to understand the command so need to find something that allows it to understand it. Figured you'd be the best person who might know the answer to that :)

**Comment by gamerforEA** [comment]
With such an old version, I can not help. I work only with 1.6.4, 1.7.10 and 1.8.

**Comment by djoveryde** [comment]
Ok thanks anyway :)
